### PR TITLE
Feat/cerdanya droneport

### PR DESCRIPTION
**Pull request by RBinsonB**
---
 
## Basic Info
 
| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   |  |
| Primary OS tested on | Ubuntu 20.04 |
| Robotic platform tested on | Laptop |
 
---
## How to run this PR feature

* This PR is only adding models, they can be checked by browsing over the files or by looking at the [companion PR for the simulation repo](https://github.com/umdlife/umd_simulation/pull/73)
 
## Description of contribution in a few bullet points
 
* Added models for Cerdanya droneport map
   * Cerdanya droneport closeup, low-res and background
   * Laptops, tables, chairs and similar props
   * Humans
   * Oak tree and hangar
   * Cars, trucks and plane
* Changed texture absolute path to relative in pine tree model (delivery world)
* Add github templates 
 
## Description of documentation updates required from your changes
 
* None

## Related PRs
* https://github.com/umdlife/umd_simulation/pull/73
 
---
 
## Future work that may be required in bullet points
 
* Use the added models to make great maps

### CODE REVIEW

**Comment by amoramar** [comment]
I can't see the changes well. I think the PR should be pointing to `master_umd` rather than `master` @RBinsonB

**Comment by RBinsonB** [comment]
Indeed I made a mistake, I thought I was targeting master_umd

**Comment by RBinsonB** [comment]
Fixed now

**Review by vicmassy — COMMENTED** [review]
Nice addition! But just wondering, do we really need all this? It is gonna increase significantly the size of our simulation image

**Comment by RBinsonB** [comment]
Not all of them to be honest, I will do some pruning

**Comment by RBinsonB** [comment]
Removed a few models and compressed the textures for the ground.

**Comment by vicmassy** [comment]
Closed for inactivity

**Comment by RBinsonB** [comment]
The files were compressed already, is it still too big?

**Pull request closed without merging**
